### ISSUE TITLE
Missing instructions after transform (AAA, AAD, ..., REP MOVS, ...)

### ISSUE THREAD

**Issue by cheery** [google/CPU-instructions#3]
After the #2 I did a new run. To make it easier for myself I moved the scripts and files into separate directory so I wouldn't accidentally lose them. After I did a bazel build and verified it succeeded, I got the pbtxt with the following command:

```
set -e

SRC=/archive/Documents/readable-intel-manual/325462-sdm-vol-1-2abcd-3abcd.pdf
DST=/archive/Documents/readable-intel-manual/instructions

pushd /archive/Documents/CPU-instructions
    bazel run cpu_instructions/tools:parse_sdm -- \
      --cpu_instructions_input_spec=$SRC \
      --cpu_instructions_output_file_base=$DST \
      --cpu_instructions_transforms=default
popd
```

I did a conversion into JSON and then retrieved the mnemonic names in each file and cross-checked them. I found out that the following came visible:

    TEST

The following instructions went to missing:

    AAA
    AAD
    AAM
    AAS
    ARPL
    BOUND
    DAA
    DAS
    FCLEX
    FINIT
    FSAVE
    FSTCW
    FSTENV
    FSTSW
    INTO
    JCXZ
    LAHF
    LDS
    LES
    POPA
    POPAD
    POPFD
    PUSHA
    PUSHAD
    PUSHFD
    REP INS
    REP LODS
    REP MOVS
    REP OUTS
    REP STOS
    REPE CMPS
    REPE SCAS
    REPNE CMPS
    REPNE SCAS
    SAHF
    XACQUIRE
    XLAT
    XRELEASE

This is interesting, because in the `instructions.pbtxt` "XLAT" and "DAA" appears to be present, but they are missing from the `_transformed.pbtxt`.

The manual used here was: Combined Volumes: 1, 2A, 2B, 2C, 2D, 3A, 3B, 3C, 3D and 4, Order Number: 325462-062US, March 2017

**Comment by gchatelet** [comment]
So this is actually _expected_. We filter out some instructions in [cpu_instructions/x86/cleanup_instruction_set_removals.cc](https://github.com/google/CPU-instructions/blob/master/cpu_instructions/x86/cleanup_instruction_set_removals.cc).

- The instructions that are "32 bits only" are removed because they will not execute in 64 bits mode (the default for nowadays processors). If you need them you can disable `RemoveNonEncodableInstructions` in the aforementioned file.
- We also remove  the `REP` prefixed instructions because `MOVS` and `REP MOVS` are technically the same instruction - only prefixed. We intend to add a field on the instruction to know if the instruction is prefixable with `REP`. If you need them you can disable `RemoveRepAndRepneInstructions` in the aforementioned file.
